import { Capacitor, registerPlugin } from '@capacitor/core';

/**
 * The two sounds that ship with the app, plus vibrate-only. 'high' is Beacon
 * (bright, rising, cuts through noise); 'soothe' is Drift (slow, warm, calm).
 * Both are generated by client/scripts/gen-call-sounds.mjs into
 * android/app/src/main/res/raw/ and mirrored in lib/ringtone.ts for the web.
 */
export type CallSoundSource = 'high' | 'soothe' | 'silent';

/** What an older install may still have stored. Never rejected — mapped. */
const LEGACY_SOUNDS: Record<string, CallSoundSource> = {
  chime: 'high',
  ringtone: 'high',
  alarm: 'high',
};

interface CallNotifierPlugin {
  requestPermission(): Promise<void>;
  requestMediaPermissions(): Promise<void>;
  setSoundSource(opts: { source: CallSoundSource }): Promise<void>;
  setCallUiActive(opts: { active: boolean }): Promise<void>;
  ring(opts: { displayName: string; soundSource?: CallSoundSource }): Promise<void>;
  stop(): Promise<void>;
  openSettings(): Promise<void>;
}

const CallNotifier = registerPlugin<CallNotifierPlugin>('CallNotifier');

export function getCallSoundSource(): CallSoundSource {
  try {
    const saved = localStorage.getItem('skillswap_call_sound');
    if (saved === 'high' || saved === 'soothe' || saved === 'silent') return saved;
    const migrated = saved ? LEGACY_SOUNDS[saved] : undefined;
    if (migrated) {
      // Rewrite once, so the native side is never handed a retired value.
      localStorage.setItem('skillswap_call_sound', migrated);
      return migrated;
    }
  } catch {
    // Ignored
  }
  return 'high';
}

export function setCallSoundSource(source: CallSoundSource): void {
  try {
    localStorage.setItem('skillswap_call_sound', source);
    if (Capacitor.getPlatform() === 'android') void CallNotifier.setSoundSource({ source });
  } catch {
    // Ignored
  }
}

export async function requestCallNotificationPermission(): Promise<void> {
  try {
    if (Capacitor.getPlatform() === 'android') await CallNotifier.requestPermission();
  } catch {
    // Web Preview / non-native builds have no native plugin.
  }
}

// Grants POST_NOTIFICATIONS, CAMERA + RECORD_AUDIO via the native bridge first,
// so the WebView getUserMedia calls never fail with a "microphone/camera not
// enabled" error. Also prompts (once) to allow full-screen call intents on
// Android 12+ so an incoming call takes over the screen like a real call.
export async function requestCallMediaPermissions(): Promise<void> {
  try {
    if (Capacitor.getPlatform() === 'android') await CallNotifier.requestMediaPermissions();
  } catch {
    // Non-native build — getUserMedia handles prompting.
  }
}

// Hides the Android system bars and keeps the screen on while a call rings or
// is active (a "simulated call alarm"). Restore with false when the call ends.
export async function setCallUiActive(active: boolean): Promise<void> {
  try {
    if (Capacitor.getPlatform() === 'android') await CallNotifier.setCallUiActive({ active });
  } catch {
    // Web Preview / non-native builds have no native plugin.
  }
}

export async function ringIncomingCall(peer: { displayName: string }, sound: CallSoundSource = 'high'): Promise<void> {
  try {
    if (Capacitor.getPlatform() === 'android') await CallNotifier.ring({ ...peer, soundSource: sound });
  } catch {
    // Fall back to the in-app Web Audio ringtone.
  }
}

export async function stopIncomingCallRing(): Promise<void> {
  try {
    if (Capacitor.getPlatform() === 'android') await CallNotifier.stop();
  } catch {
    // Ignored
  }
}

// Opens this app's Android Settings so a user who denied mic/camera/notification
// can re-grant the permission a call needs.
export async function openCallSettings(): Promise<void> {
  try {
    if (Capacitor.getPlatform() === 'android') await CallNotifier.openSettings();
  } catch {
    // Web Preview / non-native builds have no native plugin.
  }
}